controllers:
    resource: ../src/Controller/
    type: attribute

hello:
    path: /hello
    controller: App\Controller\HelloController::sayHello

app_home:
    path: /
    controller: App\Controller\HomeController::index
